### ISSUE TITLE
Setup Streamlit sharing

### ISSUE THREAD

**Issue by anton-sturluson** [CMU-IDS-2020/a3-schweitzer_yoo_a3#1]
Dear TAs, please add our repo to Streamlit sharing and then respond to this issue with the URL to the deployed application.

Where should we put our data folders in? Since we use over 200MB of data, we cannot put it in the same repo.

**Comment by anton-sturluson** [comment]
We reduced the size of the data and is not ready for deployment

**Comment by kunalkhadilkar** [comment]
what is your python file name? save the file as streamlit_app.py

**Comment by kunalkhadilkar** [comment]
Is your app file main.py?

**Comment by anton-sturluson** [comment]
It's changed to streamlit_app.py now. Thanks Kunal!

**Comment by kunalkhadilkar** [comment]
https://share.streamlit.io/cmu-ids-2020/a3-schweitzer_yoo_a3
